apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-disease-app
  labels:
    app: heart-disease-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heart-disease-app
  template:
    metadata:
      labels:
        app: heart-disease-app
    spec:
      containers:
      - name: heart-disease-app
        image: heart-disease-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
