apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-disease-model
  labels:
    app: heart-disease-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heart-disease-model
  template:
    metadata:
      labels:
        app: heart-disease-model
    spec:
      containers:
      - name: heart-disease-model
        image: heart-disease-model:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
