apiVersion: v1
kind: Service
metadata:
  name: heart-disease-service
  labels:
    app: heart-disease-model
spec:
  type: NodePort
  selector:
    app: heart-disease-model
  ports:
    - name: http        # required name
      port: 8000        # service port
      targetPort: 8000  # container port
      nodePort: 30080   # optional fixed NodePort
